name: MBa
on: 
  workflow_dispatch    


env:
  SERVER_HOST: '85.28.47.165'
  SERVER_USER: root
  SERVER_PATH: /var/www/trur/
# Бэкэнд в варианте сайта "a" находится в папке /var/www/trur/

jobs:

  deployJobs:
    runs-on: ubuntu-latest
    steps:
    - name: part1
      uses: actions/checkout@v2
       # Setup key
    - name: part2
      run: set -eu

    - name: part3  
      run: mkdir "$HOME/.ssh"
    
    - name: part4
      run: echo "${{ secrets.PKEY }}" > "$HOME/.ssh/key"

    - name: part5
      run: chmod 600 "$HOME/.ssh/key"

      # Deploy
    - name: part6
      run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}

    - name: part7 - Restart Express server on remote
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ secrets.PKEY }}
        script: |
           cd /var/www/trur/api
           pm2 restart backend